web:
    build:  .
    ports:
        -   "80:80"
    volumes:
        -   ./web:/var/www/html
        -   ./simple-onethink:/var/www/simple-onethink
    links:
        -   mysqldb:mysqldb

mysqldb:
    image:  mariadb:10.0
    ports:
        -   "3306:3306"
    environment:
        -   MYSQL_ROOT_PASSWORD=mysql

...
